Completed ds-prep-python-variables - Ravleen Kaur
ravvinkohli/ds-py-0122-code-solutions pull request #2
Opened 2022-01-06 08:20 UTC by ravvinkohli

![image](https://user-images.githubusercontent.com/97075003/148351599-a4519202-c7b3-4238-91b6-205df4365d86.png)

2022-01-07 19:34 UTC, TimelikeClosure requested changes

2022-01-07 19:34 UTC, TimelikeClosure commented on ds-prep-python-variables/main.py
> +from types import ClassMethodDescriptorType
Sometimes the VS Code auto-fill will add an `import` at the top of the file. It's generally safe to remove these.

2022-01-07 19:34 UTC, TimelikeClosure commented on ds-prep-python-variables/main.py
> +y = height_in_inches_float = 66.0
The value assigned to `height_in_inches_float` should be derived from the `height_in_inches` variable, not hard-coded:

---

![image](https://user-images.githubusercontent.com/16143771/148597109-eef81da4-434e-446d-9087-6160b3b312e7.png)

2022-01-07 19:34 UTC, TimelikeClosure commented on ds-prep-python-variables/main.py
> +print(nothing , type)
Your last `print` statement should output the `type` of the `nothing` variable:

---

![image](https://user-images.githubusercontent.com/16143771/148597430-31b4a814-91d8-4bcd-b542-17ec299c6749.png)

2022-01-15 21:06 UTC, JenBowman1 approved these changes

2022-01-15 21:07 UTC, merged