Completed Python Functions.
ravvinkohli/ds-py-0122-code-solutions pull request #3
Opened 2022-01-09 01:18 UTC by ravvinkohli

![image](https://user-images.githubusercontent.com/97075003/148665467-3d73f277-04b5-43c3-8211-8b17fcd74575.png)

2022-01-10 18:06 UTC, TimelikeClosure requested changes

2022-01-10 18:06 UTC, TimelikeClosure commented on ds-prep-python-functions/main.py
> +print(absolute_difference(5 , 3))
`absolute_difference` should also return a positive number if `b` is greater than `a`:

---

![image](https://user-images.githubusercontent.com/16143771/148815747-40f6783d-ba81-45c6-847d-3f3313d0b561.png)

---

In general, I'd recommend testing your functions with at least two different sets of inputs to make sure it's adapting well to different inputs.

2022-01-10 18:06 UTC, TimelikeClosure commented on ds-prep-python-functions/main.py
> +print(hours_to_minutes(2))
Please call these functions with keyword arguments, not positional arguments:

---

![image](https://user-images.githubusercontent.com/16143771/148816004-c39002ad-cb9f-4777-9b71-889a262546da.png)

2022-01-10 18:06 UTC, TimelikeClosure commented on ds-prep-python-functions/main.py
> +standardize(8 , 2 , 2)
Call each of these functions at least twice, using keyword arguments, with a different argument order in each call:

---

![image](https://user-images.githubusercontent.com/16143771/148816309-c0344e76-2e59-4429-bc26-b02bd93402aa.png)

2022-01-15 20:48 UTC, JenBowman1 approved these changes

2022-01-15 20:48 UTC, merged